const keyframes = [
    [
         "Week 1",
        [
            {"name": "Patrick Mahomes", "value": 34.9, "rank":1},
            {"name": "Josh Allen", "value":31.48, "rank":2},
            {"name": "Jalen Hurts", "value":24.7, "rank":7},
            {"name": "Austin Ekeler", "value":11.2, "rank":16},
            {"name": "Joe Burrow", "value":22.2, "rank":9},
            {"name": "Justin Jefferson", "value":39.4, "rank":0},
            {"name": "Christian McCaffrey", "value":15.7, "rank":13},
            {"name": "Tyreek Hill", "value":18, "rank":10},
            {"name": "Davante Adams", "value":30.1, "rank":3},
            {"name": "Josh Jacobs", "value":8.3, "rank":17},
            {"name": "Stefon Diggs", "value":26.2, "rank":4},
            {"name": "Travis Kelce", "value":26.1, "rank":5},
            {"name": "Geno Smith", "value":17.2, "rank":11},
            {"name": "Justin Fields", "value":14.6, "rank":14},
            {"name": "Kirk Cousins", "value":19.1, "rank":8},
            {"name": "Trevor Lawrence", "value":13.4, "rank":15},
            {"name": "Derrick Henry", "value":8.2, "rank":18},
            {"name": "Ceedee Lamb", "value":4.9, "rank":19},
            {"name": "A.J Brown", "value":25.5, "rank":6},
            {"name": "Daniel Jones", "value":16.02, "rank":12},
        ]
    ],
    [
        "Week 2",
        [
            {"name": "Patrick Mahomes", "value": 52.2, "rank":4},
            {"name": "Josh Allen", "value":61.1, "rank":1},
            {"name": "Jalen Hurts", "value":57.74, "rank":3},
            {"name": "Austin Ekeler", "value":29.6, "rank":12},
            {"name": "Joe Burrow", "value":34.78, "rank":9},
            {"name": "Justin Jefferson", "value":50.2, "rank":5},
            {"name": "Christian McCaffrey", "value":32.5, "rank":10},
            {"name": "Tyreek Hill", "value":60, "rank":2},
            {"name": "Davante Adams", "value":39.3, "rank":6},
            {"name": "Josh Jacobs", "value":17.4, "rank":18},
            {"name": "Stefon Diggs", "value":71, "rank":0},
            {"name": "Travis Kelce", "value":36.2, "rank":8},
            {"name": "Geno Smith", "value":17.2, "rank":15},
            {"name": "Justin Fields", "value":22.44, "rank":16},
            {"name": "Kirk Cousins", "value":27.92, "rank":14},
            {"name": "Trevor Lawrence", "value":31.9, "rank":11},
            {"name": "Derrick Henry", "value":16.7, "rank":19},
            {"name": "Ceedee Lamb", "value":20, "rank":17},
            {"name": "A.J Brown", "value":37.4, "rank":7},
            {"name": "Daniel Jones", "value":29.16, "rank":13},
        ]
    ],
    [
        "Week 3",
        [
            {"name": "Patrick Mahomes", "value": 69.28, "rank":3},
            {"name": "Josh Allen", "value":87.86, "rank":0},
            {"name": "Jalen Hurts", "value":85.34, "rank":2},
            {"name": "Austin Ekeler", "value":42.9, "rank":13},
            {"name": "Joe Burrow", "value":57.78, "rank":5},
            {"name": "Justin Jefferson", "value":54.6, "rank":8},
            {"name": "Christian McCaffrey", "value":46, "rank":12},
            {"name": "Tyreek Hill", "value":65.3, "rank":4},
            {"name": "Davante Adams", "value":53.5, "rank":10},
            {"name": "Josh Jacobs", "value":32.1, "rank":18},
            {"name": "Stefon Diggs", "value":85.4, "rank":1},
            {"name": "Travis Kelce", "value":54.1, "rank":9},
            {"name": "Geno Smith", "value":42.18, "rank":16},
            {"name": "Justin Fields", "value":27.38, "rank":19},
            {"name": "Kirk Cousins", "value":46.22, "rank":11},
            {"name": "Trevor Lawrence", "value":57.08, "rank":7},
            {"name": "Derrick Henry", "value":42, "rank":17},
            {"name": "Ceedee Lamb", "value":42.7, "rank":15},
            {"name": "A.J Brown", "value":56.9, "rank":8},
            {"name": "Daniel Jones", "value":42.9, "rank":14},
        ]
    ],
    [
        "Week 4",
        [
            {"name": "Patrick Mahomes", "value": 92.64, "rank":3},
            {"name": "Josh Allen", "value":111.38, "rank":0},
            {"name": "Jalen Hurts", "value":101.3, "rank":1},
            {"name": "Austin Ekeler", "value":77.8, "rank":8},
            {"name": "Joe Burrow", "value":77.86, "rank":7},
            {"name": "Justin Jefferson", "value":85.6, "rank":5},
            {"name": "Christian McCaffrey", "value":71.8, "rank":11},
            {"name": "Tyreek Hill", "value":91.2, "rank":4},
            {"name": "Davante Adams", "value":73, "rank":10},
            {"name": "Josh Jacobs", "value":66.6, "rank":13},
            {"name": "Stefon Diggs", "value":95.6, "rank":2},
            {"name": "Travis Kelce", "value":37.54, "rank":6},
            {"name": "Geno Smith", "value":73.88, "rank":9},
            {"name": "Justin Fields", "value":37.54, "rank":19},
            {"name": "Kirk Cousins", "value":59.14, "rank":18},
            {"name": "Trevor Lawrence", "value": 62.74, "rank":17},
            {"name": "Derrick Henry", "value":65.7, "rank":14},
            {"name": "Ceedee Lamb", "value":64.4, "rank":16},
            {"name": "A.J Brown", "value":71.4, "rank":12},
            {"name": "Daniel Jones", "value":64.54, "rank":15},
        ]
    ],
    [
        "Week 5",
        [
            {"name": "Patrick Mahomes", "value": 123.12, "rank":2},
            {"name": "Josh Allen", "value":146.54, "rank":0},
            {"name": "Jalen Hurts", "value":128.96, "rank":1},
            {"name": "Austin Ekeler", "value":113.7, "rank":5},
            {"name": "Joe Burrow", "value":95.14, "rank":12},
            {"name": "Justin Jefferson", "value":115.92, "rank":4},
            {"name": "Christian McCaffrey", "value":95.2, "rank":11},
            {"name": "Tyreek Hill", "value":104.2, "rank":7},
            {"name": "Davante Adams", "value":100.4, "rank":8},
            {"name": "Josh Jacobs", "value":96.2, "rank":10},
            {"name": "Stefon Diggs", "value":119.8, "rank":3},
            {"name": "Travis Kelce", "value":111.8, "rank":6},
            {"name": "Geno Smith", "value":97.9, "rank":9},
            {"name": "Justin Fields", "value":54.56, "rank":19},
            {"name": "Kirk Cousins", "value":81.38, "rank":14},
            {"name": "Trevor Lawrence", "value":73.08, "rank":18},
            {"name": "Derrick Henry", "value":92.9, "rank":13},
            {"name": "Ceedee Lamb", "value": 74.7, "rank":17},
            {"name": "A.J Brown", "value":77.6, "rank":15},
            {"name": "Daniel Jones", "value":76.92, "rank":16},
        ]
    ],
    [
        "Week 6",
        [
            {"name": "Patrick Mahomes", "value": 142.74, "rank":3},
            {"name": "Josh Allen", "value":172.9, "rank":0},
            {"name": "Jalen Hurts", "value":145.86, "rank":2},
            {"name": "Austin Ekeler", "value":138, "rank":4},
            {"name": "Joe Burrow", "value":127.64, "rank":8},
            {"name": "Justin Jefferson", "value":132.62, "rank":6},
            {"name": "Christian McCaffrey", "value":118, "rank":9},
            {"name": "Tyreek Hill", "value":133.9, "rank":5},
            {"name": "Davante Adams", "value":100.4, "rank":11},
            {"name": "Josh Jacobs", "value":96.9, "rank":14},
            {"name": "Stefon Diggs", "value":150.6, "rank":1},
            {"name": "Travis Kelce", "value":131, "rank":7},
            {"name": "Geno Smith", "value":110.58, "rank":10},
            {"name": "Justin Fields", "value":72.96, "rank":19},
            {"name": "Kirk Cousins", "value":97.88, "rank":13},
            {"name": "Trevor Lawrence", "value":97.98, "rank":12},
            {"name": "Derrick Henry", "value":92.9, "rank":16},
            {"name": "Ceedee Lamb", "value": 87.4, "rank":18},
            {"name": "A.J Brown", "value":95.3, "rank":15},
            {"name": "Daniel Jones", "value":90.44, "rank":17},
        ]
    ],
    [
        "Week 7",
        [
            {"name": "Patrick Mahomes", "value": 169.66, "rank":2},
            {"name": "Josh Allen", "value":172.9, "rank":1},
            {"name": "Jalen Hurts", "value":145.86, "rank":7},
            {"name": "Austin Ekeler", "value":174.7, "rank":0},
            {"name": "Joe Burrow", "value":166.88, "rank":3},
            {"name": "Justin Jefferson", "value":132.62, "rank":9},
            {"name": "Christian McCaffrey", "value":126.2, "rank":10},
            {"name": "Tyreek Hill", "value":148.1, "rank":5},
            {"name": "Davante Adams", "value":117.9, "rank":13},
            {"name": "Josh Jacobs", "value":133.4, "rank":8},
            {"name": "Stefon Diggs", "value":150.6, "rank":4},
            {"name": "Travis Kelce", "value":146.8, "rank":6},
            {"name": "Geno Smith", "value":123.68, "rank":11},
            {"name": "Justin Fields", "value":96.32, "rank":18},
            {"name": "Kirk Cousins", "value":97.88, "rank":17},
            {"name": "Trevor Lawrence", "value":116.68, "rank":14},
            {"name": "Derrick Henry", "value":109.7, "rank":15},
            {"name": "Ceedee Lamb", "value":98, "rank":16},
            {"name": "A.J Brown", "value":95.3, "rank":19},
            {"name": "Daniel Jones", "value":119.22, "rank":12},
        ]
    ],
    [
        "Week 8",
        [
            {"name": "Patrick Mahomes", "value": 169.66, "rank":6},
            {"name": "Josh Allen", "value":190.52, "rank":0},
            {"name": "Jalen Hurts", "value":174.26, "rank":4},
            {"name": "Austin Ekeler", "value":174.7, "rank":3},
            {"name": "Joe Burrow", "value":180.36, "rank":1},
            {"name": "Justin Jefferson", "value":148.42, "rank":8},
            {"name": "Christian McCaffrey", "value":166.46, "rank":7},
            {"name": "Tyreek Hill", "value": 179.6, "rank":2},
            {"name": "Davante Adams", "value":119.1, "rank":18},
            {"name": "Josh Jacobs", "value":140.8, "rank":12},
            {"name": "Stefon Diggs", "value":173.4, "rank":5},
            {"name": "Travis Kelce", "value":146.8, "rank":9},
            {"name": "Geno Smith", "value":142.76, "rank":11},
            {"name": "Justin Fields", "value":122.36, "rank":16},
            {"name": "Kirk Cousins", "value":121.36, "rank":17},
            {"name": "Trevor Lawrence", "value":123.5, "rank":15},
            {"name": "Derrick Henry", "value":145.5, "rank":10},
            {"name": "Ceedee Lamb", "value":116.8, "rank":19},
            {"name": "A.J Brown", "value":134.9, "rank":13},
            {"name": "Daniel Jones", "value":128.26, "rank":14},
        ]
    ],
    [
        "Week 9",
        [
            {"name": "Patrick Mahomes", "value": 203.8, "rank":2},
            {"name": "Josh Allen", "value":215.32, "rank":0},
            {"name": "Jalen Hurts", "value":194.28, "rank":5},
            {"name": "Austin Ekeler", "value":198.8, "rank":4},
            {"name": "Joe Burrow", "value":199.5, "rank":3},
            {"name": "Justin Jefferson", "value":173.92, "rank":7},
            {"name": "Christian McCaffrey", "value":166.46, "rank":10},
            {"name": "Tyreek Hill", "value":206.9, "rank":1},
            {"name": "Davante Adams", "value":155.7, "rank":13},
            {"name": "Josh Jacobs", "value":152.5, "rank":14},
            {"name": "Stefon Diggs", "value":187.7, "rank":6},
            {"name": "Travis Kelce", "value":167.4, "rank":9},
            {"name": "Geno Smith", "value":163.56, "rank":12},
            {"name": "Justin Fields", "value":165.56, "rank":11},
            {"name": "Kirk Cousins", "value":137.76, "rank":17},
            {"name": "Trevor Lawrence", "value":140.2, "rank":16},
            {"name": "Derrick Henry", "value":169, "rank":8},
            {"name": "Ceedee Lamb", "value": 116.8, "rank":19},
            {"name": "A.J Brown", "value":150.8, "rank":15},
            {"name": "Daniel Jones", "value":128.26, "rank":18},
        ]
    ],
    [
        "Week 10",
        [
            {"name": "Patrick Mahomes", "value": 234.94, "rank":0},
            {"name": "Josh Allen", "value":234.92, "rank":1},
            {"name": "Jalen Hurts", "value":216.08, "rank":3},
            {"name": "Austin Ekeler", "value":212.1, "rank":5},
            {"name": "Joe Burrow", "value":199.5, "rank":8},
            {"name": "Justin Jefferson", "value":209.22, "rank":6},
            {"name": "Christian McCaffrey", "value":184.16, "rank":10},
            {"name": "Tyreek Hill", "value": 222.3, "rank":2},
            {"name": "Davante Adams", "value":183.3, "rank":11},
            {"name": "Josh Jacobs", "value":175.1, "rank":14},
            {"name": "Stefon Diggs", "value":212.5, "rank":4},
            {"name": "Travis Kelce", "value":187.5, "rank":9},
            {"name": "Geno Smith", "value":182.76, "rank":12},
            {"name": "Justin Fields", "value":204.46, "rank":7},
            {"name": "Kirk Cousins", "value":153.24, "rank":17},
            {"name": "Trevor Lawrence", "value":161.16, "rank":15},
            {"name": "Derrick Henry", "value":177.7, "rank":13},
            {"name": "Ceedee Lamb", "value":154.8, "rank":16},
            {"name": "A.J Brown", "value":152.5, "rank":18},
            {"name": "Daniel Jones", "value":146.54, "rank":19},
        ]
    ],
    [
        "Week 11",
        [
            {"name": "Patrick Mahomes", "value": 262.4, "rank":0},
            {"name": "Josh Allen", "value":247.5, "rank":1},
            {"name": "Jalen Hurts", "value":240.28, "rank":2},
            {"name": "Austin Ekeler", "value":230.1, "rank":3},
            {"name": "Joe Burrow", "value":226.2, "rank":6},
            {"name": "Justin Jefferson", "value":215.52, "rank":10},
            {"name": "Christian McCaffrey", "value":201.76, "rank":12},
            {"name": "Tyreek Hill", "value":222.3, "rank":8},
            {"name": "Davante Adams", "value":216.4, "rank":9},
            {"name": "Josh Jacobs", "value":194.1, "rank":13},
            {"name": "Stefon Diggs", "value":227.3, "rank":4},
            {"name": "Travis Kelce", "value":223, "rank":7},
            {"name": "Geno Smith", "value":182.76, "rank":14},
            {"name": "Justin Fields", "value":227.08, "rank":5},
            {"name": "Kirk Cousins", "value":155.44, "rank":19},
            {"name": "Trevor Lawrence", "value":161.16, "rank":18},
            {"name": "Derrick Henry", "value":203.06, "rank":11},
            {"name": "Ceedee Lamb", "value":164.3, "rank":16},
            {"name": "A.J Brown", "value":161.5, "rank":17},
            {"name": "Daniel Jones", "value":171.18, "rank":15},
        ]
    ],
    [
        "Week 12",
        [
            {"name": "Patrick Mahomes", "value": 280.8, "rank":0},
            {"name": "Josh Allen", "value":277.42, "rank":1},
            {"name": "Jalen Hurts", "value":270.1, "rank":2},
            {"name": "Austin Ekeler", "value":255.1, "rank":3},
            {"name": "Joe Burrow", "value":244.2, "rank":6},
            {"name": "Justin Jefferson", "value":244.86, "rank":5},
            {"name": "Christian McCaffrey", "value":210.66, "rank":13},
            {"name": "Tyreek Hill", "value":237.3, "rank":9},
            {"name": "Davante Adams", "value":230.8, "rank":10},
            {"name": "Josh Jacobs", "value":242.4, "rank":7},
            {"name": "Stefon Diggs", "value":249, "rank":4},
            {"name": "Travis Kelce", "value":238.7, "rank":8},
            {"name": "Geno Smith", "value":202.08, "rank":14},
            {"name": "Justin Fields", "value":227.08, "rank":11},
            {"name": "Kirk Cousins", "value":177.3, "rank":18},
            {"name": "Trevor Lawrence", "value":186.1, "rank":15},
            {"name": "Derrick Henry", "value":217.76, "rank":12},
            {"name": "Ceedee Lamb", "value":182, "rank":17},
            {"name": "A.J Brown", "value":174.1, "rank":19},
            {"name": "Daniel Jones", "value":185.7, "rank":16},
        ]
    ],
    [
        "Week 13",
        [
            {"name": "Patrick Mahomes", "value": 300.62, "rank":1},
            {"name": "Josh Allen", "value":294.34, "rank":2},
            {"name": "Jalen Hurts", "value":304.5, "rank":0},
            {"name": "Austin Ekeler", "value":268.3, "rank":6},
            {"name": "Joe Burrow", "value":274.24, "rank":3},
            {"name": "Justin Jefferson", "value":263.46, "rank":8},
            {"name": "Christian McCaffrey", "value":239.26, "rank":12},
            {"name": "Tyreek Hill", "value":266.9, "rank":7},
            {"name": "Davante Adams", "value":268.5, "rank":5},
            {"name": "Josh Jacobs", "value":263.4, "rank":9},
            {"name": "Stefon Diggs", "value":271.2, "rank":4},
            {"name": "Travis Kelce", "value":246.3, "rank":11},
            {"name": "Geno Smith", "value":225.06, "rank":13},
            {"name": "Justin Fields", "value":246.34, "rank":10},
            {"name": "Kirk Cousins", "value":189.12, "rank":19},
            {"name": "Trevor Lawrence", "value":202.46, "rank":17},
            {"name": "Derrick Henry", "value":223.56, "rank":14},
            {"name": "Ceedee Lamb", "value": 202.4, "rank":18},
            {"name": "A.J Brown", "value":206, "rank":15},
            {"name": "Daniel Jones", "value":202.8, "rank":16},
        ]
    ],
    [
        "Week 14",
        [
            {"name": "Patrick Mahomes", "value": 320.4, "rank":1},
            {"name": "Josh Allen", "value":314.92, "rank":2},
            {"name": "Jalen Hurts", "value":334.88, "rank":0},
            {"name": "Austin Ekeler", "value":292.7, "rank":4},
            {"name": "Joe Burrow", "value":290.8, "rank":6},
            {"name": "Justin Jefferson", "value":296.76, "rank":3},
            {"name": "Christian McCaffrey", "value":268.56, "rank":10},
            {"name": "Tyreek Hill", "value":291, "rank":5},
            {"name": "Davante Adams", "value":278.6, "rank":8},
            {"name": "Josh Jacobs", "value":282.8, "rank":7},
            {"name": "Stefon Diggs", "value":277.9, "rank":9},
            {"name": "Travis Kelce", "value":257.4, "rank":11},
            {"name": "Geno Smith", "value":245.62, "rank":13},
            {"name": "Justin Fields", "value":246.34, "rank":12},
            {"name": "Kirk Cousins", "value":214.12, "rank":18},
            {"name": "Trevor Lawrence", "value":235.88, "rank":15},
            {"name": "Derrick Henry", "value":244.06, "rank":14},
            {"name": "Ceedee Lamb", "value":210.7, "rank":19},
            {"name": "A.J Brown", "value":223, "rank":16},
            {"name": "Daniel Jones", "value":222.16, "rank":17},
        ]
    ],
    [
        "Week 15",
        [
            {"name": "Patrick Mahomes", "value": 353.14, "rank":1},
            {"name": "Josh Allen", "value":350.78, "rank":2},
            {"name": "Jalen Hurts", "value":369.58, "rank":0},
            {"name": "Austin Ekeler", "value":307.7, "rank":6},
            {"name": "Joe Burrow", "value":315.6, "rank":4},
            {"name": "Justin Jefferson", "value":327.06, "rank":3},
            {"name": "Christian McCaffrey", "value": 294.36, "rank":8},
            {"name": "Tyreek Hill", "value": 312.9, "rank":5},
            {"name": "Davante Adams", "value":285.4, "rank":10},
            {"name": "Josh Jacobs", "value":295.8, "rank":7},
            {"name": "Stefon Diggs", "value":288.6, "rank":9},
            {"name": "Travis Kelce", "value":277.9, "rank":11},
            {"name": "Geno Smith", "value":260.94, "rank":15},
            {"name": "Justin Fields", "value":269.92, "rank":13},
            {"name": "Kirk Cousins", "value":246.52, "rank":17},
            {"name": "Trevor Lawrence", "value":262.7, "rank":14},
            {"name": "Derrick Henry", "value":270.36, "rank":12},
            {"name": "Ceedee Lamb", "value":230.4, "rank":19},
            {"name": "A.J Brown", "value":250.1, "rank":16},
            {"name": "Daniel Jones", "value":232.06, "rank":18},
        ]
    ],   
    [
        "Week 16",
        [
            {"name": "Patrick Mahomes", "value": 376.9, "rank":0},
            {"name": "Josh Allen", "value":373.76, "rank":1},
            {"name": "Jalen Hurts", "value":369.58, "rank":2},
            {"name": "Austin Ekeler", "value":331.6, "rank":5},
            {"name": "Joe Burrow", "value":339.1, "rank":4},
            {"name": "Justin Jefferson", "value":358.36, "rank":3},
            {"name": "Christian McCaffrey", "value":308.16, "rank":7},
            {"name": "Tyreek Hill", "value": 327.2, "rank":6},
            {"name": "Davante Adams", "value":288.9, "rank":12},
            {"name": "Josh Jacobs", "value":301.8, "rank":8},
            {"name": "Stefon Diggs", "value":293.2, "rank":10},
            {"name": "Travis Kelce", "value":295.2, "rank":9},
            {"name": "Geno Smith", "value":273.14, "rank":15},
            {"name": "Justin Fields", "value":279.78, "rank":14},
            {"name": "Kirk Cousins", "value":270.68, "rank":16},
            {"name": "Trevor Lawrence", "value":280.96, "rank":13},
            {"name": "Derrick Henry", "value":288.96, "rank":11},
            {"name": "Ceedee Lamb", "value": 264.4, "rank":18},
            {"name": "A.J Brown", "value":250.1, "rank":17},
            {"name": "Daniel Jones", "value":232.06, "rank":19},
        ]
    ],
    [
        "Week 17",
        [
            {"name": "Patrick Mahomes", "value": 402.42, "rank":0},
            {"name": "Josh Allen", "value":373.76, "rank":1},
            {"name": "Jalen Hurts", "value":369.58, "rank":2},
            {"name": "Austin Ekeler", "value":363.7, "rank":3},
            {"name": "Joe Burrow", "value":339.1, "rank":7},
            {"name": "Justin Jefferson", "value":360.86, "rank":4},
            {"name": "Christian McCaffrey", "value":339.46, "rank":6},
            {"name": "Tyreek Hill", "value":342.9, "rank":5},
            {"name": "Davante Adams", "value":323.2, "rank":8},
            {"name": "Josh Jacobs", "value":321.3, "rank":9},
            {"name": "Stefon Diggs", "value":293.2, "rank":12},
            {"name": "Travis Kelce", "value":306.5, "rank":10},
            {"name": "Geno Smith", "value":290.26, "rank":13},
            {"name": "Justin Fields", "value":295.98, "rank":11},
            {"name": "Kirk Cousins", "value":278.58, "rank":19},
            {"name": "Trevor Lawrence", "value":285.44, "rank":17},
            {"name": "Derrick Henry", "value":288.96, "rank":15},
            {"name": "Ceedee Lamb", "value": 285.4, "rank":18},
            {"name": "A.J Brown", "value":286.1, "rank":16},
            {"name": "Daniel Jones", "value":289, "rank":14},
        ]
    ],
    [
        "Week 18",
        [
            {"name": "Patrick Mahomes", "value": 421, "rank":0},
            {"name": "Josh Allen", "value":396, "rank":1},
            {"name": "Jalen Hurts", "value":394, "rank":2},
            {"name": "Austin Ekeler", "value":382, "rank":3},
            {"name": "Joe Burrow", "value":362, "rank":5},
            {"name": "Justin Jefferson", "value":380, "rank":4},
            {"name": "Christian McCaffrey", "value":359, "rank":6},
            {"name": "Tyreek Hill", "value":355, "rank":7},
            {"name": "Davante Adams", "value":338, "rank":8},
            {"name": "Josh Jacobs", "value":328, "rank":9},
            {"name": "Stefon Diggs", "value":309, "rank":12},
            {"name": "Travis Kelce", "value":316, "rank":10},
            {"name": "Geno Smith", "value":311, "rank":11},
            {"name": "Justin Fields", "value":299, "rank":17},
            {"name": "Kirk Cousins", "value":302, "rank":16},
            {"name": "Trevor Lawrence", "value":295, "rank":19},
            {"name": "Derrick Henry", "value":306, "rank":14},
            {"name": "Ceedee Lamb", "value":305, "rank":15},
            {"name": "A.J Brown", "value":296, "rank":18},
            {"name": "Daniel Jones", "value":309, "rank":13},
        ]
    ]
]

export {keyframes};